### ISSUE TITLE
Implement Contribution License Agreement

### ISSUE THREAD

**Issue by jpdillingham** [MESAInternational/B2MML-BatchML#10]
- [ ] Research and suggest a draft CLA
- [ ] Ratify agreement (with whom?)
- [ ] Implement CLA and appropriate signature workflow (TBD pending research)

**Comment by jpdillingham** [comment]
When completed, the CLA is to be implemented on the remainder of MESAInternational repositories, both existing and future.

**Comment by BrentHumphreys** [comment]
Example CLA - https://cla.opensource.microsoft.com/

**Comment by Dennis-Brandl** [comment]
This has been passed of to MESA. If they decide they need a CLA, and provide the method to set it up, we will incorporate into B2MML.
