### ISSUE TITLE
TransactionProfile.xsd - Revision History Typo

### ISSUE THREAD

**Issue by andreb1972** [MESAInternational/B2MML-BatchML#15]
Typo:
Revision History:  "Added new objects from Part 4 and Part 4" should probably be "Added new objects from Part 2 and Part 4"

**Comment by Dennis-Brandl** [comment]
Yes,looks like a type, should be corrected.

**Comment by Dennis-Brandl** [comment]
Corrected in January 2020 Sprint

**Comment by JoeDo** [comment]
Confirmed that the change has been made in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
Revision history removed, everything to be gin GitHub. Issue closed.
