### ISSUE TITLE
TransactionProfile.xsd - Enumeration value

### ISSUE THREAD

**Issue by andreb1972** [MESAInternational/B2MML-BatchML#16]
Related to element in TransactionProfile.xsd:
```
<xsd:complexType name="TransactionNoun1Type">	<xsd:simpleContent>	
      <xsd:restriction base="CodeType">
```
Missing 
`<xsd:enumeration value="MASTER DATA PROFILE"/>`

**Comment by Dennis-Brandl** [comment]
Based on the February 11, 2018 meeting, this will be fixed. In the future we will ask the submitter to make a PULL request with the patch.

**Comment by Dennis-Brandl** [comment]
To be fixed in the January 2020 Sprint

**Comment by JoeDo** [comment]
Confirmed that the change has been made in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
Fixed in to be released version, issue closed.
