### ISSUE TITLE
CommonExtensions .xsd

### ISSUE THREAD

**Issue by andreb1972** [MESAInternational/B2MML-BatchML#18]
Typo in CommonExtensions.xsd and also in OperationsEvent.xsd

The group name in CommonExtensions should be EventClassProperty
```
 <xsd:group name = "OperationsEvenClassProperty">
                <xsd:sequence>
                        <!-- add extended elements here -->
                </xsd:sequence>
        </xsd:group>
```

The reference to this type is in OperationsEvent.xsd:
```
<xsd:complexType name="OperationsEventClassPropertyType">
	<xsd:group ref="Extended:OperationsEvenClassProperty" minOccurs="0" maxOccurs="1"/>
```

**Comment by Dennis-Brandl** [comment]
Based on the February 11, 2018 meeting, this will be fixed. In the future we will ask the submitter to make a PULL request with the patch.

**Comment by Dennis-Brandl** [comment]
To be fixed in the January 2020 Sprint

**Comment by JoeDo** [comment]
Confirmed that the change has been made in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
Corrected, closing issue.
