### ISSUE TITLE
AllSchemas.xsd - Missing elements

### ISSUE THREAD

**Issue by andreb1972** [MESAInternational/B2MML-BatchML#19]
The following elements are missing from AllSchemas.xsd
```

<xsd:include schemaLocation="B2MML-MasterDataProfile.xsd"/>
<xsd:include schemaLocation="B2MML-OperationalLocation.xsd"/>
<xsd:include schemaLocation="B2MML-OperationsEvent.xsd"/>
<xsd:include schemaLocation="B2MML-OperationsPerformanceTypes.xsd"/>
<xsd:include schemaLocation="B2MML-TestSpecification.xsd"/>
<xsd:include schemaLocation="B2MML-WorkDefinition.xsd"/>
<xsd:include schemaLocation="B2MML-WorkPerformance.xsd"/>
```

Duplicate element:
`<xsd:include schemaLocation="B2MML-WorkCapability.xsd"/>`

**Comment by Dennis-Brandl** [comment]
Based on the February 11, 2018 meeting, this will be fixed. In the future we will ask the submitter to make a PULL request with the patch.

**Comment by Dennis-Brandl** [comment]
To be fixed in the January 2020 Sprint

**Comment by JoeDo** [comment]
Confirmed that the change has been made in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
Closing this issue.
