### ISSUE TITLE
First Draft B2MML and BatchML V0601

### ISSUE THREAD

**Issue by Dennis-Brandl** [MESAInternational/B2MML-BatchML#2]
This is ready for initial review. There is no documentation yet, and I havn't completly updated the internal change history. But these can come later once we make sure that everything is ready. 
Dennis

**Comment by JoeDo** [comment]
@Dennis-Brandl Should we close this now that V0700 has been posted with documentation?

**Comment by Dennis-Brandl** [comment]
Close now that V0700 is posted.
