### ISSUE TITLE
MasterDataProfile.xsd - Incomplete include elements

### ISSUE THREAD

**Issue by andreb1972** [MESAInternational/B2MML-BatchML#21]
I'm not familiar with the MasterDataProfile concept yet, but the `<xsd:include>` looks incomplete.  The issue linked below has the missing elements if they need to be updated.

Potentially related to : [https://github.com/MESAInternational/B2MML-BatchML/issues/19](url)

**Comment by Dennis-Brandl** [comment]
Unclear what is missing, please clarify. Thanks Dennis

**Comment by Dennis-Brandl** [comment]
To be fixed in the January 2020 Sprint

**Comment by JoeDo** [comment]
Confirmed that a reference to the MasterDataProfile schema has been added to AllSchemas.xsd in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
Closing issue.
