### ISSUE TITLE
MasterDataProfile.xsd - Unit of measure

### ISSUE THREAD

**Issue by andreb1972** [MESAInternational/B2MML-BatchML#22]
We have a UnitOfMeasureType defined in Common.xsd.  

This element  in MasterDataProfile.xsd uses IDandDescriptionType.  Consider changing this to UnitOfMeasureType for consistency
`
<xsd:element name="UnitOfMeasure" type="IDandDesciptionType" minOccurs="0" maxOccurs="unbounded"/>
`
If this is not an issue, then consider changing the element name to remove ambiguity.

**Comment by Dennis-Brandl** [comment]
Based on the February 11, 2018 meeting, this was rejected. In TR95.01 the unit of measure elements are defined to include the Unit Of Measure (as a string) and a description.  This change would have removed the description.
