### ISSUE TITLE
MasterDataProfile.xsd - Typo IDandDescriptionType

### ISSUE THREAD

**Issue by andreb1972** [MESAInternational/B2MML-BatchML#23]
The element name attribute has a typo:
`	<xsd:complexType name="IDandDesciptionType">`

IDandDesciptionType = IDandDescriptionType

Elements that reference this type will also need to be corrected:

```
<xsd:complexType name="MasterDataProfileType">
		<xsd:sequence>
			<xsd:element name="Header" type="MasterDataProfileHeaderType"/>
			<xsd:element name="UnitOfMeasure" type="IDandDesciptionType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="DataType" type="IDandDesciptionType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ValueKey" type="IDandDesciptionType" minOccurs="0" maxOccurs="unbounded"/>
```

**Comment by Dennis-Brandl** [comment]
I failed spelling, yes it should be IDandDescriptionType.

**Comment by Dennis-Brandl** [comment]
To be fixed in the January 2020 Sprint

**Comment by JoeDo** [comment]
Confirmed that the change has been made in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
Closing issue.
