### ISSUE TITLE
TestSpecification.xsd - Optional ID

### ISSUE THREAD

**Issue by andreb1972** [MESAInternational/B2MML-BatchML#24]
In all (or most) other schemas, the ID of the primary entity is always a required element.  In the TestSpecification,  this ID is optional.
```
<xsd:complexType name="TestSpecificationType">
		<xsd:sequence>
			<xsd:element name="ID" type="IdentifierType" minOccurs="0"/>
```

TestSpecificationID is referenced in other schemas (like ProcessSegment and OpsPerformance), so consider making the ID a required element
```
<xsd:complexType name="TestSpecificationType">
		<xsd:sequence>
			<xsd:element name="ID" type="IdentifierType" minOccurs="1"/>
```

**Comment by Dennis-Brandl** [comment]
Yes, looks like a bug/type. I believe it should be required. (actually just remove the "minOccurs")

**Comment by Dennis-Brandl** [comment]
Based on the February 11, 2018 meeting, this will be fixed. In the future we will ask the submitter to make a PULL request with the patch.

**Comment by Dennis-Brandl** [comment]
To be fixed in the January 2020 Sprint

**Comment by JoeDo** [comment]
Confirmed that the change has been made in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
Closing issue.
