### ISSUE TITLE
add Disposition attribute to MaterialLotType and MaterialSubLotType 

### ISSUE THREAD

**Issue by racheliurui** [MESAInternational/B2MML-BatchML#36]
### Background

ADD element name = "Disposition", type = "DispositionType" (#35 ) to to MaterialLotType and MaterialSubLotType align with updated ISA-95 Part 2 Material Lot and Material SubLot Object. Add DispositionType to Common Schema.

### Impacted Types
B2MML - Material.xsd

- MaterialLotType
- MaterialSubLotType

### Supporting Document
>ISA-950002
Section 5.7.6 and 5.7.8
Table 69 – Material lot attributes
Table 73 – Material sublot attributes

**Comment by Dennis-Brandl** [comment]
To be fixed in the January 2020 Sprint

**Comment by JoeDo** [comment]
Confirmed that the change has been made in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
To be included in the soon to be released version. Issue closed.
