### ISSUE TITLE
Example BatchML

### ISSUE THREAD

**Issue by vaibhavkhanduja** [MESAInternational/B2MML-BatchML#4]
Hi,

Is there a place where I can find example BatchMLs? I am writing code and want to test my parser.

Thanks,

**Comment by vaibhavkhanduja** [comment]
@BrentHumphreys @JoeDo @Emers @agileteams @jvieille Any thoughts here?

**Comment by Emers** [comment]
Hi,
Unfortunately we only have a couple of examples, and these are for older versions.  We are also using a Yahoo Group as a general list server (we are still in progress of fully moving onto GitHub), I've posted a request to that list server.  You can use this URL to see any responses - I administer the Yahoo Group so if you make a request to join I'll accept it.
https://groups.yahoo.com/neo/groups/mesa-xml-wg/conversations/messages

Dave Emerson - emers

**Comment by vaibhavkhanduja** [comment]
@Emers Thanks I have sent you a request to join the group.
