### ISSUE TITLE
Element Typo "AssemblylDefinitionID"

### ISSUE THREAD

**Issue by bebedizo** [MESAInternational/B2MML-BatchML#46]
# Issue
I'd like to point you to a typo in the Material Information Schema (XSD) of the downloadable B2MML Specification.

File: B2MML-V0600-Material.xsd
Line: 246
```
<xsd:element name = "AssemblylDefinitionID"
-----------------------------^
```

should probably say (without the "l" after "Assembly"):
```
<xsd:element name = "AssemblyDefinitionID"
```

This typo also propagates to the corresponding documentation:

File: B2MML-V0600-Material.pdf
Page: 7 (Page 9 in PDF Viewer)

The figure showing internals of MaterialDefinition also says "AssemblylDefinitionID"
instead of
"AssemblyDefinitionID".

This error/typo was introduced in V0500.

# Resolution
I have seen in the repo, that this issue has been fixed; however, it renders previous versions invalid. In case you would like to keep the schema backwards-compatible (and a little more complex), you could add the following trick.

According to <https://www.w3schools.com/xml/schema_complex_subst.asp> it is possible to allow for a different spelling of one and the same XML tag.

The erroneous file B2MML-V0600-Material.xsd could therefore be fixed by adding the following statement to it:

```
<xsd:element name="AssemblyDefinitionID" substitutionGroup="AssemblylDefinitionID"/>
```

or, vice-versa, define the incorrect spelling as an alternative to the correct spelling:
```
<xsd:element name="AssemblylDefinitionID" substitutionGroup="AssemblyDefinitionID"/>
```

**Comment by Dennis-Brandl** [comment]
We will not update V600 
This was fixed in V0700.
