### ISSUE TITLE
Update WorkflowSpecificationInformationType to align with ISA-950004

### ISSUE THREAD

**Issue by vitalJP** [MESAInternational/B2MML-BatchML#48]
**Background** 
_Explicitly Align B2MML with updated 950004 Workflow Specification Model by having "WorkflowSpecificationInformationType" address the 1st order objects used as master data._

**Supporting Document**
_ISA950004_
Clause 6.16.1 Workflow specification model, Figure 5 – Workflow specification model

**Impacted Types and Solution**
_B2MML-WorkflowSpecification.xsd
complexType name = "WorkflowSpecificationInformationType"_

CHANGE:  
- element name = "WorkflowSpecificationType"   type = "WorkflowSpecificationTypeType"  
    TO:   "WorkflowSpecificationNodeType"   type = "WorkflowSpecificationNodeTypeType" 

ADD:
- element name = "WorkflowSpecificationConnectionType"   type = "WorkflowSpecificationConnectionTypeType" minOccurs = "0" maxOccurs = "unbounded"/>

**Comment by Dennis-Brandl** [comment]
The proposed change does not match ISA 95 Part 4. The Node is just a step in a workflow, the WorkflowSpecificationInformation contains a set of WorkflowSpecifications, which contain nodes and connections. 
The WorkflowSpecificaionType is missing the relationship to other IncludesThePropertiesOf
Not shown in ISA 95 Part 4 is a WorkflowSpecificationType, which NodeSpecifications and ConnectionSpecifications.  This was added as the WorkflowSpecificationTypeType.

**Comment by JoeDo** [comment]
Confirmed the addition of an IncludesThePropertiesOf element in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
Changed in the soon to be released version, Issue closed.
