### ISSUE TITLE
Add OperationsEventClassID to OperationsEventDefinitionType in OperationsEvent.xsd to align with updated 950002

### ISSUE THREAD

**Issue by vitalJP** [MESAInternational/B2MML-BatchML#56]
complexType name = "OperationsEventDefinitionType"> to align with update 950002, Operations Event Model

**Solution**
ADD element name = "OperationsEventClassID    type = "IdentifierType"  minOccurs = "0" maxOccurs = "unbounded"/>

**Supporting Document**
950002, Clause 5.11.5 Operations event definition, Table 131 – Operations event definition relationship roles

**Impacted Types**
B2MML OperationsEvent.xsd:  "OperationsEventDefinitionType"

**Comment by Dennis-Brandl** [comment]
To be fixed in January 2020 Sprint

**Comment by JoeDo** [comment]
Confirmed that the change has been made in the January-2020-Sprint branch. I'll circle back and Close this issue after the changes have been merged into Master.

**Comment by Dennis-Brandl** [comment]
Fixed as above in the soon to be released version. 
Issue closed.
