### ISSUE TITLE
B2MML-MasterDataProfile - extra space in  PublishedDate minOccurs=" 0"

### ISSUE THREAD

**Issue by jrmannen** [MESAInternational/B2MML-BatchML#67]
<xsd:element name = "PublishedDate"       type = "DateTimeType"        minOccurs=" 0"/>
<xsd:element name = "PublishedDate"       type = "DateTimeType"        minOccurs="0"/>

remove extra space before zero,
might need to be without space ... issue when for example generating JAXB classes using tool xjc

**Comment by Dennis-Brandl** [comment]
Definitely a problem.  I will fix.
