### ISSUE TITLE
V7 Publicity Opportunity

### ISSUE THREAD

**Issue by Emers** [MESAInternational/B2MML-BatchML#72]
MESA would like to publicize the V7 release.  If you are willing to write a blog entry respond to this issue with your interest, or even better with a blog entry.  I will then put MESA marketing in touch with you.

A blog is 500-700 words, the full MESA guidelines are at http://www.mesa.org/en/newsevents/Submit-Content.asp

If you are interested in organizing and/or presenting in a webinar publicizing v7 let me know.

**Comment by gerardmoloneyetpartners** [comment]
I will pass this message along to John.

**Comment by Dennis-Brandl** [comment]
Closed, we shaould start a new one for the latest merge (Version 7.0.1)
