### ISSUE TITLE
Change OpEquipmentRequirementType\EquipmentLevel codetype to EquipmentLevelType

### ISSUE THREAD

**Issue by gerardmoloneyetpartners** [MESAInternational/B2MML-BatchML#74]
The B2MML-Common.xsd defines the codetype for  OpEquipmentRequirementType\EquipmentLevel codetype=HierarchyScopeType

This should be CodeType=EquipmentLevel

Additionally, the Sequence should relocate the EquipmentLevel to be immediately after the EquipmentID for easier understanding.

Existing XSD (lines 893 to 912) with the issue at Line 904
![image](https://user-images.githubusercontent.com/54049079/120592073-cd513f80-c46f-11eb-895a-2442167377b1.png)

Proposed Fix - Relocate to line 898, and change codetype=EquipmentLevelType
![image](https://user-images.githubusercontent.com/54049079/120592253-1d300680-c470-11eb-9446-fc7a6622e058.png)

**Comment by h28669** [comment]
I agree. It looks like wrong type in current schema definition.

**Comment by ETPartners** [comment]
Any movement on this please guys?

**Comment by gerardmoloneyetpartners** [comment]
Any movement on this guys?

**Comment by Dennis-Brandl** [comment]
Yes, they need to be changed in the next version.

**Comment by Dennis-Brandl** [comment]
Fixed with latest merge with main
