### ISSUE TITLE
Long term support for XML vs JSON

### ISSUE THREAD

**Issue by ArnoClaeys** [MESAInternational/B2MML-BatchML#76]
Within our research group we use ISA-95 for modelling manufacturing information and, correspondingly, B2MML for data exchange. Currently, we serialize B2MML objects in XML format based on the XSD schemas provided on this repository. Nevertheless, some of the research and technology partners prefer JSON over XML for data exchange and processing. I did notice the addition of the B2MML-JSON schema, but as stated in the readme, this was generated from the XSDs and there was no checking nor validation of this JSON-schema. 

Currently, we are drawing our roadmap for the next few years. During this process there is some discussion whether we should use XML or JSON serialization (or both?). In order to support this decision, I was wondering how this is included in the B2MML roadmap. **Will there be long term support for XML or will the focus shift to JSON(-LD)?** 

Many thanks!

**Comment by Dennis-Brandl** [comment]
I believe that there will be continuing support for XML, just because many existing vendors support some form of B2MML XML.  the B2MML-JSON version has only seen limited use so far, so I believe the focus will remain on XML with automatic conversion to the JSON format.
