### ISSUE TITLE
Add WorkDefinition extensions group 

### ISSUE THREAD

**Issue by ArnoClaeys** [MESAInternational/B2MML-BatchML#80]
As in some cases, if not in most cases, extensions on WorkMaster also apply on WorkDirective, it would be convenient to also add a extensions group to WorkDefinition.

See proposed commit: https://github.com/MESAInternational/B2MML-BatchML/pull/77/commits/77de6350d61aeac233cf7463a3f8e07919537553

**Comment by Dennis-Brandl** [comment]
Good idea, something we missed.
We have an extension in the WorkDefinitionInformation, which is a container object.
We have extensions in WorkMasters and in WorkDirectives.
This changes adds a common extension to the shared information between all WorkMasters and WorkDirectives.
This is not a breaking change. See three types of extensions in figure below.
image
![image](https://user-images.githubusercontent.com/16944002/218812970-82258cfe-0ff7-4918-b211-4bcce8edfd9f.png)

**Comment by ArnoClaeys** [comment]
Looks good. Thanks!
